#!/bin/bash -eu

export CLICKHOUSENAME="LOCAL_CLICKHOUSE_SERVER"
export CLICKHOUSEPORTA=8123
export CLICKHOUSEPORTB=9000
export CLICKHOUSEDB="LOCAL_CLICKHOUSE_DATABASE_NAME"
export CLICKHOUSEUSER="LOCAL_CLICKHOUSE_DATABASE_USER"
export CLICKHOUSEPASS="LOCAL_CLICKHOUSE_DATABASE_USER_PASSWORD"